version: "3.5"
services:

  postgres:
    image: postgres:14.3-alpine
    container_name: taskdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "taskdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Password"
      PG_DATA: ./snap/postgres/data/pgdata
